advanced_ml:
  focal_loss:
    alpha: 1.0
    enable: false
    gamma: 2.0
  interpretability:
    lime: false
    partial_dependence: true
    permutation_importance: true
    shap: true
  validation:
    bootstrap_validation: false
    individual_cv: true
    spatial_cv: true
    temporal_cv: true
ai_analysis:
  behavior_analysis: true
  comprehensive_report: true
  cost_sensitive:
    enable: true
    focal_loss:
      alpha: 1.0
      gamma: 2.0
    method: scale_pos_weight
  enable: true
  ensemble:
    enable: true
    methods:
    - voting
    - stacking
    voting_type: soft
  feature_analysis: true
  openai:
    max_tokens: 2000
    model: gpt-4
    temperature: 0.3
  optimization:
    enable: true
    n_trials: 50
    study_name: shark_habitat_optimization
    timeout: 1800
  performance_analysis: true
  recommendations: true
  sampling:
    k_neighbors: 5
    strategy: smote
cv:
  folds: 5
  primary_strategy: stratified_kfold
  random_state: 42
  scheme: spatial
  strategies:
    group_kfold:
      description: Group K-Fold by shark individual
      n_splits: 5
      random_state: null
      shuffle: false
    stratified_kfold:
      description: Stratified K-Fold for class balance
      n_splits: 5
      random_state: 42
      shuffle: true
    temporal_split:
      description: Temporal split for time series data
      gap: 0
      max_train_size: null
      n_splits: 5
      random_state: null
      shuffle: false
      test_size: null
  validation_splits: 5
data:
  feature_engineering:
    enable: true
    feature_selection: true
    interaction_features: true
    polynomial_features: false
    temporal_features: true
  quality_thresholds:
    max_missing_ratio: 0.1
    min_feature_variance: 1e-6
    min_samples_per_class: 1
  training_data_path: data/interim/training_data_realistic_features.csv
  validation:
    check_data_types: true
    check_missing: true
    check_outliers: true
    outlier_threshold: 3.0
data_augmentation:
  enable: true
  feature_perturbation:
    augmentation_factor: 1.5
    perturbation_std: 0.05
  methods:
  - noise_injection
  - feature_perturbation
  - temporal_augmentation
  noise_injection:
    augmentation_factor: 2
    noise_std: 0.01
  temporal_augmentation:
    augmentation_factor: 1.2
    time_window: 7
documentation:
  generate_docs: true
  reproducibility:
    save_data_hash: true
    save_model_hash: true
    save_random_state: true
  save_config: true
  versioning:
    enable: true
    save_versions: true
    track_changes: true
early_stopping:
  enable: true
  min_delta: 0.001
  mode: max
  monitor_metric: roc_auc
  n_iter_no_change: 10
  patience: 10
  restore_best_weights: true
  tol: 0.0001
  validation_fraction: 0.2
ensemble:
  bagging:
    bootstrap: true
    bootstrap_features: false
    max_features: 0.8
    max_samples: 0.8
    n_estimators: 10
  enable: true
  methods:
  - voting
  - stacking
  - bagging
  stacking:
    cv: 5
    final_estimator: logistic_regression
    passthrough: false
  voting:
    voting_type: soft
    weights:
    - 0.4
    - 0.3
    - 0.3
evaluation:
  calibration_curves: true
  feature_importance: true
  metrics:
  - roc_auc
  - pr_auc
  - tss
  - f1
  - precision
  - recall
  - accuracy
  - specificity
  - sensitivity
  shap_explanations: true
  targets:
    f1: 0.35
    pr_auc: 0.4
    roc_auc: 0.7
    tss: 0.25
experimental:
  advanced_sampling:
    custom_samplers: false
    enable: true
    methods:
    - smote
    - adasyn
    - borderline_smote
  automl:
    enable: false
    framework: auto-sklearn
  neural_networks:
    architectures:
    - mlp
    - cnn
    - lstm
    enable: false
feature_selection:
  correlation_threshold: 0.95
  enable: true
  feature_importance_threshold: 0.01
  methods:
  - variance_threshold
  - correlation_filter
  - mutual_info
  - recursive_elimination
  mutual_info_k: 10
  recursive_elimination:
    cv: 3
    n_features_to_select: 20
    scoring: roc_auc
  variance_threshold: 0.01
logging:
  file: logs/ai_enhanced_training.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
model:
  algorithms:
  - xgboost
  - random_forest
  - lightgbm
  lightgbm:
    colsample_bytree: 0.8
    learning_rate: 0.05
    max_depth: 6
    n_estimators: 500
    num_leaves: 31
    reg_alpha: 0.1
    reg_lambda: 1.0
    scale_pos_weight: auto
    subsample: 0.8
  optimization:
    enable_optuna: true
    n_trials: 100
    timeout: 3600
  random_forest:
    class_weight: balanced
    max_depth: 10
    max_features: sqrt
    min_samples_leaf: 2
    min_samples_split: 5
    n_estimators: 300
  xgboost:
    colsample_bytree: 0.8
    learning_rate: 0.05
    max_depth: 6
    n_estimators: 500
    reg_alpha: 0.1
    reg_lambda: 1.0
    scale_pos_weight: auto
    subsample: 0.8
monitoring:
  benchmarks:
    baseline_roc_auc: 0.536
    improvement_threshold: 0.02
    target_roc_auc: 0.65
  early_stopping:
    enable: true
    min_delta: 0.001
    patience: 10
  memory_monitoring: true
  progress_tracking: true
output:
  model_format: pkl
  reports:
    ai_analysis_report: true
    feature_importance_report: true
    performance_report: true
    training_summary: true
  results_format: json
  save_models: true
  save_results: true
  visualizations:
    calibration_curves: true
    feature_importance: true
    model_comparison: true
    performance_plots: true
    shap_plots: true
overfitting_prevention:
  data_validation:
    check_data_leakage: true
    check_feature_leakage: true
    check_spatial_leakage: true
    check_temporal_leakage: true
  steps:
  - data_validation
  - feature_selection
  - cross_validation
  - regularization
  - early_stopping
  - ensemble_training
  - validation_monitoring
  training_strategy:
    stratify_validation: true
    temporal_split: true
    use_validation_set: true
    validation_size: 0.2
regularization:
  lightgbm:
    bagging_fraction: 0.8
    bagging_freq: 5
    colsample_bytree: 0.8
    feature_fraction: 0.8
    learning_rate: 0.05
    max_depth: 6
    min_child_samples: 20
    min_gain_to_split: 0.1
    n_estimators: 500
    num_leaves: 31
    reg_alpha: 0.1
    reg_lambda: 1.0
    subsample: 0.8
  random_forest:
    bootstrap: true
    max_depth: 10
    max_features: sqrt
    max_samples: 0.8
    min_samples_leaf: 5
    min_samples_split: 10
    n_estimators: 300
    random_state: 42
  xgboost:
    colsample_bylevel: 0.8
    colsample_bynode: 0.8
    colsample_bytree: 0.8
    gamma: 0.1
    learning_rate: 0.05
    max_depth: 6
    min_child_weight: 3
    n_estimators: 500
    reg_alpha: 0.1
    reg_lambda: 1.0
    subsample: 0.8
resources:
  distributed:
    backend: dask
    enable: false
  gpu:
    device: auto
    enable: false
  memory_limit: 8GB
  n_jobs: -1
validation:
  data_integrity:
    checks:
    - missing_values
    - outliers
    - data_types
    - ranges
    enable: true
  model_validation:
    cross_validation: true
    enable: true
    holdout_test: true
    temporal_validation: true
  performance_validation:
    enable: true
    minimum_metrics:
      pr_auc: 0.1
      roc_auc: 0.5
      tss: -0.5
    target_metrics:
      pr_auc: 0.35
      roc_auc: 0.65
      tss: 0.2
validation_monitoring:
  early_stopping_patience: 15
  enable: true
  learning_rate_reduction:
    factor: 0.5
    min_lr: 1.0e-06
    patience: 5
  metrics:
  - roc_auc
  - pr_auc
  - f1_score
  - precision
  - recall
  model_checkpointing:
    max_checkpoints: 5
    save_best: true
    save_frequency: 50
  overfitting_threshold: 0.05
  validation_frequency: 10
